name: Install and run syncing
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '*/15 * * * *'
jobs:
  sync:
    environment: LIVE
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - run: |
          pip install -r requirements.txt
      - shell: bash
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          fedflare epel.cloud
      - uses: gautamkrishnar/keepalive-workflow@v1